# Form implementation generated from reading ui file '.\history_beta.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(619, 406)
        self.imageViewerLabel = QtWidgets.QLabel(parent=Form)
        self.imageViewerLabel.setGeometry(QtCore.QRect(20, 20, 291, 321))
        self.imageViewerLabel.setObjectName("imageViewerLabel")
        self.translatedTextsEdit = QtWidgets.QPlainTextEdit(parent=Form)
        self.translatedTextsEdit.setGeometry(QtCore.QRect(360, 20, 241, 321))
        self.translatedTextsEdit.setReadOnly(True)
        self.translatedTextsEdit.setObjectName("translatedTextsEdit")
        self.previousImgBtn = QtWidgets.QPushButton(parent=Form)
        self.previousImgBtn.setGeometry(QtCore.QRect(170, 360, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.previousImgBtn.setFont(font)
        icon = QtGui.QIcon.fromTheme("applications-accessories")
        self.previousImgBtn.setIcon(icon)
        self.previousImgBtn.setFlat(False)
        self.previousImgBtn.setObjectName("previousImgBtn")
        self.nextImgBtn = QtWidgets.QPushButton(parent=Form)
        self.nextImgBtn.setGeometry(QtCore.QRect(350, 360, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.nextImgBtn.setFont(font)
        icon = QtGui.QIcon.fromTheme("applications-accessories")
        self.nextImgBtn.setIcon(icon)
        self.nextImgBtn.setFlat(False)
        self.nextImgBtn.setObjectName("nextImgBtn")
        self.idxViewerLabel = QtWidgets.QLabel(parent=Form)
        self.idxViewerLabel.setGeometry(QtCore.QRect(280, 370, 49, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.idxViewerLabel.setFont(font)
        self.idxViewerLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.idxViewerLabel.setWordWrap(False)
        self.idxViewerLabel.setObjectName("idxViewerLabel")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.imageViewerLabel.setText(_translate("Form", "[Images]"))
        self.previousImgBtn.setText(_translate("Form", "<"))
        self.nextImgBtn.setText(_translate("Form", ">"))
        self.idxViewerLabel.setText(_translate("Form", "-/-"))
