# Form implementation generated from reading ui file '.\main_window_2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(491, 552)
        self.windowComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.windowComboBox.setGeometry(QtCore.QRect(20, 50, 451, 22))
        self.windowComboBox.setObjectName("windowComboBox")
        self.translateButton = QtWidgets.QPushButton(parent=Dialog)
        self.translateButton.setGeometry(QtCore.QRect(390, 520, 75, 24))
        self.translateButton.setObjectName("translateButton")
        self.translatedTextsEdit = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.translatedTextsEdit.setGeometry(QtCore.QRect(20, 90, 451, 421))
        self.translatedTextsEdit.setReadOnly(True)
        self.translatedTextsEdit.setObjectName("translatedTextsEdit")
        self.historyButton = QtWidgets.QPushButton(parent=Dialog)
        self.historyButton.setGeometry(QtCore.QRect(30, 520, 75, 24))
        self.historyButton.setObjectName("historyButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.translateButton.setText(_translate("Dialog", "RUN"))
        self.historyButton.setText(_translate("Dialog", "HISTORY"))
