# Form implementation generated from reading ui file '.\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.windowComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.windowComboBox.setGeometry(QtCore.QRect(20, 50, 361, 22))
        self.windowComboBox.setObjectName("windowComboBox")
        self.translateButton = QtWidgets.QPushButton(parent=Dialog)
        self.translateButton.setGeometry(QtCore.QRect(310, 260, 75, 24))
        self.translateButton.setObjectName("translateButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.translateButton.setText(_translate("Dialog", "PushButton"))
